import type { Material, Task } from "./domain";

export const seedTasks: Task[] = [
  {
    id: "08dc2e63",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-07-31",
    dueTime: "19:00",
    title: "Proyecto Final-Webinar",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: 46,
    visibleToReaders: true,
    calendarEventId: "5jftp0e77tvis88s063fsrv8sk@google.com",
    lastSync: "2026-05-31",
  },
  {
    id: "98b8736d",
    course: "Alteraciones de la Conducta",
    dueDate: "2026-06-15",
    dueTime: "23:59",
    title: "Ensayo Película \"SICK OF MYSELF\"",
    deliveryType: "Proyecto",
    status: "Se entrega hoy",
    daysRemaining: 0,
    notes: "Solo se permitirá el 50% de uso de IA; si se excede, se reducirán 2 puntos.",
    visibleToReaders: true,
    calendarEventId: "32uamjsiubite52ljecl04ihog@google.com",
    lastSync: "2026-05-31",
  },
  {
    id: "5ca21689",
    course: "Psicología en la Problemática Social Mexicana",
    dueDate: "2026-06-15",
    dueTime: "19:00",
    title: "Exposición Proyecto de Investigación",
    materialNeeded: "Presentación",
    deliveryType: "Proyecto",
    status: "Se entrega hoy",
    daysRemaining: 0,
    visibleToReaders: true,
    calendarEventId: "660uh6ijsvl8rvocv68lohrdcg@google.com",
  },
  {
    id: "63da2dad",
    course: "Teoría y Práctica de Procesos Grupales",
    dueDate: "2026-06-15",
    dueTime: "15:15",
    title: "Examen Procesos Grupales",
    materialNeeded: "Carpeta de Drive con presentaciones de clases",
    materialUrl: "https://drive.google.com/drive/folders/106SJxqRpg7vbKMQHoiA0349LdNqHDVrL?usp=sharing",
    deliveryType: "Examen",
    status: "Se entrega hoy",
    daysRemaining: 0,
    visibleToReaders: true,
    calendarEventId: "41q2afhmbecd428p7opuid6bvo@google.com",
  },
  {
    id: "6a22aa98",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-06-16",
    dueTime: "17:00",
    title: "Examen Primer Parcial",
    materialNeeded: "Apuntes de clases",
    deliveryType: "Examen",
    status: "Pendiente",
    daysRemaining: 1,
    visibleToReaders: true,
    calendarEventId: "ooqjj2c2bk21l196vp7b0acplc@google.com",
  },
  {
    id: "6dbd9f4a",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-06-09",
    dueTime: "17:00",
    title: "Propuesta de programa de Condicionamiento",
    materialNeeded: "Recurso multimedia de 1 minuto",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -6,
    visibleToReaders: false,
  },
];

export const seedMaterials: Material[] = [
  {
    id: "MAT-APA7",
    type: "PDF",
    scope: "Artículos de Investigación",
    name: "Resumen APA 7",
    url: "https://drive.google.com/file/d/1JCDpyhZXzk0ULcNSzoAQoAbVUalGv4ad/view?usp=sharing",
    previewUrl: "https://drive.google.com/file/d/1JCDpyhZXzk0ULcNSzoAQoAbVUalGv4ad/preview",
    updatedAt: "2026-06-09",
  },
  {
    id: "MAT-WAIS",
    type: "PDF",
    scope: "Tests",
    name: "Manual de aplicación WAIS IV",
    url: "https://drive.google.com/file/d/1s9z4x696bNwrVUDmt3vW5BLPgvWZ7Pmj/view?usp=sharing",
    previewUrl: "https://drive.google.com/file/d/1s9z4x696bNwrVUDmt3vW5BLPgvWZ7Pmj/preview",
    updatedAt: "2026-06-01",
  },
  {
    id: "MAT-SAMPIERI",
    type: "PDF",
    scope: "Metodología",
    name: "Metodología de la Investigación Sampieri",
    url: "https://drive.google.com/file/d/1R0oUcA7UDUk2d_KUnqqx1jdge1tzhtLx/view?usp=sharing",
    previewUrl: "https://drive.google.com/file/d/1R0oUcA7UDUk2d_KUnqqx1jdge1tzhtLx/preview",
    updatedAt: "2026-06-01",
  },
];
