import type { ConfigColumn, GroupMember, Material, Task } from "./domain";

export const seedTasks: Task[] = [
  {
    id: "b39f93db",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-06-12",
    dueTime: "20:00",
    title: "Tarea 2. Infografía",
    materialNeeded: "Leer las págs. 96 a 109 del texto La educación encierra un tesoro y sintetizar en una infografía.",
    deliveryType: "Tarea",
    status: "Pendiente",
    daysRemaining: -3,
    visibleToReaders: true,
    platformUrl: "https://teams.cloud.microsoft/",
  },
  {
    id: "8ab22cbe",
    course: "Evaluación Psicológica I",
    dueDate: "2026-06-11",
    dueTime: "15:00",
    title: "Valoración Neuroconductual del Desarrollo del Lactante \"VANEDELA\"",
    materialNeeded: "Manual de aplicación VANEDELA y lactante menor a 2 años",
    materialUrl: "https://drive.google.com/file/d/1nt8buMX9xZEqmjRN_R_bi6wFduVGS3lu/view?usp=sharing",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: -4,
    visibleToReaders: true,
  },
  {
    id: "a4f97582",
    course: "Psicología en la Problemática Social Mexicana",
    dueDate: "2026-06-11",
    dueTime: "19:00",
    title: "Adelanto Proyecto de investigación",
    materialNeeded: "Manual APA 7ma Edición",
    materialUrl: "https://drive.google.com/file/d/1JCDpyhZXzk0ULcNSzoAQoAbVUalGv4ad/view?usp=sharing",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: -4,
    visibleToReaders: true,
    platformUrl: "https://teams.cloud.microsoft/",
  },
  {
    id: "5ca21689",
    course: "Psicología en la Problemática Social Mexicana",
    dueDate: "2026-06-15",
    dueTime: "19:00",
    title: "Exposición Proyecto de Investigación",
    materialNeeded: "Presentación",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: 0,
    visibleToReaders: true,
    calendarEventId: "660uh6ijsvl8rvocv68lohrdcg@google.com",
  },
  {
    id: "98b8736d",
    course: "Alteraciones de la Conducta",
    dueDate: "2026-06-15",
    dueTime: "23:59",
    title: "Ensayo Película \"SICK OF MYSELF\"",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: 0,
    notes: "Solo se permitirá el 50% de uso de IA; si se excede, se reducirán 2 puntos.",
    visibleToReaders: true,
    calendarEventId: "32uamjsiubite52ljecl04ihog@google.com",
  },
  {
    id: "08dc2e63",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-07-31",
    dueTime: "19:00",
    title: "Proyecto Final-Webinar",
    deliveryType: "Proyecto",
    status: "Pendiente",
    daysRemaining: 46,
    visibleToReaders: true,
    calendarEventId: "5jftp0e77tvis88s063fsrv8sk@google.com",
  },
  {
    id: "63da2dad",
    course: "Teoría y Práctica de Procesos Grupales",
    dueDate: "2026-06-15",
    dueTime: "15:15",
    title: "Examen Procesos Grupales",
    materialNeeded: "Carpeta de Drive con presentaciones de clases",
    materialUrl: "https://drive.google.com/drive/folders/106SJxqRpg7vbKMQHoiA0349LdNqHDVrL?usp=sharing",
    deliveryType: "Examen",
    status: "Pendiente",
    daysRemaining: 0,
    visibleToReaders: true,
    calendarEventId: "41q2afhmbecd428p7opuid6bvo@google.com",
  },
  {
    id: "6a22aa98",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-06-16",
    dueTime: "17:00",
    title: "Examen Primer Parcial",
    materialNeeded: "Apuntes de clases",
    deliveryType: "Examen",
    status: "Pendiente",
    daysRemaining: 1,
    visibleToReaders: true,
    calendarEventId: "ooqjj2c2bk21l196vp7b0acplc@google.com",
  },
  {
    id: "tar-1",
    course: "Teoría y Práctica de Procesos Grupales",
    dueDate: "2026-05-18",
    dueTime: "15:00",
    title: "T1- Teoria de Campo",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -28,
    visibleToReaders: false,
  },
  {
    id: "tar-2",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-05-18",
    dueTime: "19:00",
    title: "T1- Mapa Conceptual",
    materialNeeded: "Capítulo Problemas básicos de psicología del aprendizaje de Rubén Ardila",
    materialUrl: "https://saberespsi.wordpress.com/wp-content/uploads/2016/09/ardila-psicologc3ada-del-aprendizaje.pdf",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -28,
    visibleToReaders: false,
  },
  {
    id: "2b585118",
    course: "Psicología del Aprendizaje",
    dueDate: "2026-05-19",
    dueTime: "23:59",
    title: "Ensayo: TEMAS FUNDAMENTALES PARA LAS TEORÍAS DEL APRENDIZ",
    materialNeeded: "Libro Teorías del aprendizaje Schunk",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -27,
    visibleToReaders: false,
  },
  {
    id: "tar-3",
    course: "Evaluación Psicológica I",
    dueDate: "2026-05-21",
    dueTime: "15:00",
    title: "T1- Organizador Vizual",
    materialUrl: "https://gc.scalahed.com/recursos/files/r161r/w25759w/S1_R1.pdf",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -25,
    visibleToReaders: false,
  },
  {
    id: "d3c5f742",
    course: "Evaluación Psicológica I",
    dueDate: "2026-05-28",
    dueTime: "15:00",
    title: "Linea de Desarrollo",
    materialNeeded: "DIGITAL",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -18,
    visibleToReaders: false,
  },
  {
    id: "82470b3e",
    course: "Psicología en la Problemática Social Mexicana",
    dueDate: "2026-05-28",
    dueTime: "19:00",
    title: "Investigar sobre tema del proyecto",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -18,
    notes: "En el cuaderno mínimo dos páginas",
    visibleToReaders: false,
  },
  {
    id: "f71bee43",
    course: "Teoría y Práctica de Procesos Grupales",
    dueDate: "2026-06-01",
    dueTime: "15:00",
    title: "T2-Propiedades del grupo ( revisión película Juego de Honor)",
    materialNeeded: "Película disponible en Amazon Prime, Apple TV, Google Play movies. Gratis en Mercado Play",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -14,
    visibleToReaders: false,
  },
  {
    id: "8f8b66c8",
    course: "Teoría y Práctica de Procesos Grupales",
    dueDate: "2026-06-08",
    dueTime: "15:00",
    title: "T3- Resumen - Ámbitos de aplicación grupal",
    deliveryType: "Tarea",
    status: "Entregado",
    daysRemaining: -7,
    visibleToReaders: false,
  },
];

export const seedMaterials: Material[] = [
  { id: "abuso-1", type: "PDF", scope: "Abuso Sexual", name: "3-Abuso sexual Infantil.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-2", type: "PDF", scope: "Abuso Sexual", name: "Abuso sexual Infantil-1.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-3", type: "PDF", scope: "Abuso Sexual", name: "Abuso Sexual Menores.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-4", type: "PDF", scope: "Abuso Sexual", name: "Atencion en abuso sexua linfantil.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-5", type: "PDF", scope: "Abuso Sexual", name: "El cristal roto_ Sobreviviendo al abuso sexual.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-6", type: "PDF", scope: "Abuso Sexual", name: "EVALUACION PSICOLOGICA EN ABUSO SEXUAL.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-7", type: "PDF", scope: "Abuso Sexual", name: "los-juegos-de-la-deteccion-de-abuso-sexual.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "abuso-8", type: "PDF", scope: "Abuso Sexual", name: "Manual abuso sexual.pdf", url: "https://drive.google.com/", previewUrl: "https://drive.google.com/", folder: "Psicología Clínica" },
  { id: "apa7", type: "PDF", scope: "Articulos de Investigación", name: "Resumen-APA-7-ed-2019-11-6.pdf", url: "https://drive.google.com/file/d/1JCDpyhZXzk0ULcNSzoAQoAbVUalGv4ad/view?usp=sharing", previewUrl: "https://drive.google.com/file/d/1JCDpyhZXzk0ULcNSzoAQoAbVUalGv4ad/preview", folder: "Articulos de Investigación" },
];

export const seedMembers: GroupMember[] = [
  { controlNumber: "28386", email: "altamirano_28386@univdep.edu.mx", fullName: "Altamirano Huerta Selene Anahí", attended: false, licenseIssue: true, authIssue: false },
  { controlNumber: "28206", email: "arciga_28206@univdep.edu.mx", fullName: "Arciga Barriga Bibiana Alejandra", attended: false, licenseIssue: true, authIssue: false },
  { controlNumber: "27942", email: "becerril_27942@univdep.edu.mx", fullName: "Becerril Galván Danna Karola", attended: false, licenseIssue: false, authIssue: true },
  { controlNumber: "27954", email: "Blanco_27954@univdep.edu.mx", fullName: "Blanco González Arely Alejandra", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28138", email: "campos_28138@univdep.edu.mx", fullName: "Campos Cano Estefania", attended: false, licenseIssue: true, authIssue: false },
  { controlNumber: "28156", email: "cruz_28156@univdep.edu.mx", fullName: "Cruz Reyes Gael Emiliano", attended: false, licenseIssue: false, authIssue: true },
  { controlNumber: "28073", email: "davila_28073@univdep.edu.mx", fullName: "Dávila Velásquez Montserrat", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28252", email: "fierro_28252@univdep.edu.mx", fullName: "Fierro Cabrera Janet", attended: false, licenseIssue: true, authIssue: false },
  { controlNumber: "28451", email: "hernandez_28451@univdep.edu.mx", fullName: "Hernández Cabrera Hector Manuel", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28200", email: "Hernandez_28200@univdep.edu.mx", fullName: "Hernandez Hernandez Mauricio", attended: false, licenseIssue: false, authIssue: true },
  { controlNumber: "28380", email: "Lara_28380@univdep.edu.mx", fullName: "Lara Campa Libertad Llanara", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28723", email: "lezama_28723@univdep.edu.mx", fullName: "Lezama Morales Estephania", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28657", email: "marquez_28657@univdep.edu.mx", fullName: "Márquez Pichardo Laila Ximena", attended: false, licenseIssue: false, authIssue: false },
  { controlNumber: "28699", email: "martinez_28699@univdep.edu.mx", fullName: "Martínez Hernández Ricardo", attended: false, licenseIssue: true, authIssue: true },
  { controlNumber: "28607", email: "ortega_28607@univdep.edu.mx", fullName: "Ortega Palencia Arely", attended: false, licenseIssue: true, authIssue: false },
];

export const seedConfigColumns: ConfigColumn[] = [
  { name: "No. Control", key: "no_control", active: true, checkboxes: false, fixed: true },
  { name: "Nombre completo", key: "nombre_completo", active: true, checkboxes: false, fixed: true },
  { name: "Mail", key: "e_mail", active: true, checkboxes: true, fixed: true },
  { name: "Correo electronico", key: "correo_electronico", active: true, checkboxes: false, fixed: true },
  { name: "Asistió", key: "columna_1", active: true, checkboxes: true, fixed: false },
  { name: "Problema licencia", key: "columna_2", active: true, checkboxes: true, fixed: false },
  { name: "Problema Auth", key: "columna_3", active: true, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_4", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_5", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_6", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_7", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_8", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_9", active: false, checkboxes: true, fixed: false },
  { name: "⠀", key: "columna_10", active: false, checkboxes: true, fixed: false },
];
