-- Persistent task notifications generated by database triggers.

create or replace function app_private.notify_task_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  notification_kind text;
  notification_title text;
  notification_body text;
begin
  if TG_OP = 'INSERT' then
    if new.visible_to_students is not true or new.status in ('Entregado', 'Cancelado') then
      return new;
    end if;

    notification_kind := 'task_created';
    notification_title := 'Nueva tarea: ' || new.title;
  elsif TG_OP = 'UPDATE' then
    if new.visible_to_students is not true or new.status in ('Entregado', 'Cancelado') then
      return new;
    end if;

    if not (
      old.title is distinct from new.title
      or old.due_date is distinct from new.due_date
      or old.due_time is distinct from new.due_time
      or old.status is distinct from new.status
      or old.material_needed is distinct from new.material_needed
      or old.material_url is distinct from new.material_url
      or old.platform_url is distinct from new.platform_url
      or old.notes is distinct from new.notes
    ) then
      return new;
    end if;

    notification_kind := 'task_updated';
    notification_title := 'Tarea actualizada: ' || new.title;
  else
    return new;
  end if;

  select coalesce(c.name, 'Sin materia') || ' · ' || to_char(new.due_date, 'DD/MM/YYYY') || ' ' || coalesce(to_char(new.due_time, 'HH24:MI'), '23:59')
  into notification_body
  from public.courses c
  where c.id = new.course_id;

  notification_body := coalesce(notification_body, 'Sin materia · ' || to_char(new.due_date, 'DD/MM/YYYY') || ' ' || coalesce(to_char(new.due_time, 'HH24:MI'), '23:59'));

  insert into public.notifications(profile_id, kind, priority, title, body, entity, entity_id, action_url, created_by)
  select
    p.id,
    notification_kind,
    case when new.due_date <= current_date + 1 then 'high' else 'normal' end,
    notification_title,
    notification_body,
    'tasks',
    new.id::text,
    '/?task=' || new.id::text,
    public.current_profile_id()
  from public.app_profiles p
  left join public.notification_preferences np on np.profile_id = p.id
  where p.active = true
    and p.role = 'student'
    and coalesce(np.in_app_enabled, true) = true
    and coalesce((np.categories ->> notification_kind)::boolean, true) = true;

  return new;
end;
$$;

drop trigger if exists trg_notify_task_change on public.tasks;
create trigger trg_notify_task_change
after insert or update on public.tasks
for each row
execute function app_private.notify_task_change();
